### ISSUE TITLE
Error when "include php"

### ISSUE THREAD

**Issue by virse** [steampixel/docker-tor-hidden-service#1]
Hey there,

thanks for the docker-service!

I ran into an issue using your repo. 

I include a php-file in my index-php to count the visitors:

`<?php
$file = "aufrufe.txt"; // Diese Variable enthält den pfad der datei besucher.txt
$fp = fopen($file,"r"); // besucher.txt zum lesen öffnen
$zahl = fgets($fp,10); // Den inhalt von besucher.txt in die Variable $zahl einlesen
fclose($fp); // besucher.txt wieder schliessen
$zahl++; // Variable $zahl um 1 erhöhen
$fp = fopen($file,"w");// besucher.txt zum lesen öffnen
fputs($fp,$zahl);// Besucherzahl ($zahl) in besucher.txt speichern
fclose($fp);//besucher.txt schliessen
echo $zahl;// Besucherzahl ausgeben
?>`

I already build the apache-php-docker without the security things (disable_functions = phpinfo,mail,exec,passthru,shell_exec,system,proc_open,popen,curl_exec,curl_multi_exec,parse_ini_file,show_source';) in the Dockerfile / the php.ini. But with the same result of getting a 500 error in the log file of the apache-docker.

The 500 error occurs also when I call directly the include-php as .onion/filename.php

Do you habe any hints on that?

Thx, mike

**Comment by steampixel** [comment]
Hi, what is the message oft the error?

Am 8. Januar 2022 15:36:51 MEZ schrieb virse ***@***.***>:

**Comment by virse** [comment]
Thx for your reply.

This is log entry when I try to call the .onion/zaehler.php:

`172.17.0.4 - - [08/Jan/2022:19:01:50 +0000] "GET /zaehler.php HTTP/1.1" 500 169 "-" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"
"http://gapp2buwawjgpcjx7rwltrn4uwenr7kim3lz7wpyqwcduzxckv7tipqd.onion/zaehler.php" "Mozilla/5.0 (Windows NT 10.0; rv:91.0) Gecko/20100101 Firefox/91.0"`

The side itself is blank, what is okay cause it only counts +1 in a textfile which should be then displayed on the index.php

greets

**Comment by steampixel** [comment]
Hi,
This is not the PHP error message. This is the Apache Log.
please enable error reporting by putting this to the head of your index.php file:
```
ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
```
Then reload the page. The error message should appear. Do not forget to remove this later...

**Comment by virse** [comment]
Thx for the hint.

I was able to find the error. The "tor-user" wasn't able to write the textfile due to missing rights. 

Thx!
